all:
	javac -d classes/ -cp classes/ IllegalNumberException.java
	javac -d classes/ -cp classes/ MMBurgersInterface.java
	javac -d classes/ -cp classes/ MMBurgers.java
	javac -d classes/ -cp classes/ TestCase5.java
	java -cp classes/ TestCase5

clean:
	rm classes/IllegalNumberException.class classes/MMBurgersInterface.class classes/MMBurgers.class classes/TestCase5.class
 
